# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.7'
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Test (race)
        run: go test ./... -race
      - name: Vet
        run: go vet ./...
      - name: Staticcheck
        env:
          GOTOOLCHAIN: local
          CGO_ENABLED: 0
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck -checks=all,-ST1006 ./...

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
          fail_ci_if_error: true
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Bench
        run: go test -bench=. -benchmem ./...
