name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run test
      run: make test
      
    - name: Run bench
      run: make bench
      
    - name: Run bench long
      run: make bench long
      
    - name: Run vet
      run: make vet

    - name: Run lint
      run: make lint

    - name: Run ci
      run: make ci

      
